In [18]:
import statistics as sts
import pandas as pd
import seaborn as srn

In [19]:
dataframe = pd.read_csv('tempo.csv', sep=";")

dataframe.head()

  Aparencia  Temperatura  Umidade       Vento Jogar
0       sol           85     85.0       FALSO   nao
1       sol           80     90.0  VERDADEIRO   nao
2   nublado           83     86.0       FALSO   sim
3     chuva           70      NaN       FALSO   sim
4     chuva           68     80.0       FALSO   sim

In [20]:
#Aparência
dataframe.groupby(['Aparencia']).size()

Aparencia
chuva      5
menos      1
nublado    3
sol        5
dtype: int64

In [21]:
#Remover valore errados de aparência
dataframe.loc[dataframe['Aparencia'] == 'menos', 'Aparencia'] = 'sol'

dataframe.groupby(['Aparencia']).size()

Aparencia
chuva      5
nublado    3
sol        6
dtype: int64

In [22]:
#Temperatura
dataframe['Temperatura'].describe()
dataframe.loc[(dataframe['Temperatura'] > 130) | (dataframe['Temperatura'] < -130) ]

  Aparencia  Temperatura  Umidade  Vento Jogar
7       sol         1220     95.0  FALSO   nao

In [23]:
#Substituir valores fora do dominio pela mediana
medianaTemperatura = sts.median(dataframe['Temperatura'])
dataframe.loc[(dataframe['Temperatura'] > 130) |(dataframe['Temperatura'] < -130), 'Temperatura'] = medianaTemperatura
dataframe.loc[(dataframe['Temperatura'] > 130) |(dataframe['Temperatura'] < -130) ]

C:\Users\lepab\AppData\Local\Temp\ipykernel_13116\1245594955.py:3: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value '73.5' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  dataframe.loc[(dataframe['Temperatura'] > 130) |(dataframe['Temperatura'] < -130), 'Temperatura'] = medianaTemperatura

Empty DataFrame
Columns: [Aparencia, Temperatura, Umidade, Vento, Jogar]
Index: []

In [24]:
#Umidade
dataframe['Umidade'].describe()

count     13.000000
mean      89.769231
std       34.540203
min       65.000000
25%       70.000000
50%       85.000000
75%       90.000000
max      200.000000
Name: Umidade, dtype: float64

In [27]:
#Substituir valores fora do dominio pela mediana
medianaUmidade = sts.median(dataframe['Umidade'])
dataframe.loc[(dataframe['Umidade'] > 100) | (dataframe['Umidade'] < 0), 'Umidade'] = medianaUmidade
dataframe['Umidade'].describe()

count    13.000000
mean     80.961538
std       9.896257
min      65.000000
25%      70.000000
50%      85.000000
75%      90.000000
max      95.000000
Name: Umidade, dtype: float64